### ISSUE TITLE
Ignore port number

### ISSUE THREAD

**Issue by chripede** [schourode/canonicalize#1]
This package works great localhost and on standard hosting, but it fails to work on AppHarbor.

They have a loadbalancer in front of their webservers, which redirects to ports other than 80. This means that requests for http://domain.com/Page ends up in Request.Url as a request for http://domain.com:15162/Page.

I've thought about adding a UseStandardHttpPort strategy, but I think it will just cause an endless redirect. 

Perhaps add a setting to ignore port number?

**Comment by schourode** [comment]
So, AppHarbor's load balancer accepts requests on port 80 and acts as a reverse proxy, forwarding the request to port 15162 where the actual web application is hosted. I don't remember implementing any strategies restricting port numbers, so I am not sure why Canonicalize would break in such a setup.

What does your Canonicalize setup/configuration look like? Exactly how does it fail (redirect loop, yellow screen, etc.)?

**Comment by chripede** [comment]
It forwards the request to another port, but on their internal network. I can't reach my site on the forwarded port.

My setup is NoWww, Lowercase

The problem is that canonicalize compares the entire request url to the one that has been through all strategies.

Ex. 1:
http://domain.com/ex/path -> Request.Url = http://domain.com:15162/ex/path. Nothing happens here, because it's all lowercase and without www.

Ex. 2:
http://domain.com/ex/Path -> Request.Url = http://domain.com:15162/ex/Path -> Redirects to http://domain.com:15162/ex/path

**Comment by schourode** [comment]
Thanks for the clarification. I see the problem now, and you are absolutely right, this cannot be solved by any `IUrlStrategy` implementation as the interface looks today.

This issue could be solved if we had some way to define a "low importance" strategy, which can not trigger a redirect on its own. I have a few ideas as to how this could be made possible:
1. Add a new interface – subtyping the existing `IUrlStrategy` – for low importance strategies. No new methods needs to be added to this interface, but the `UrlCanonicalizeRoute` is modified to handle the two types of strategies differently.
2. Change the return type of `IUrlStrategy.Apply` to `bool`, allowing the strategy to return `true` if a redirect is required, `false` if not. Existing strategies would need to be rewritten to return true when they make a change. The new `AppHarborStrategy` would change the port to 80, but always return `false`.
3. Similar to #2, but using a `ref bool` argument instead of a return type `bool`. This opens some interesting possibilities for strategy implementations, knowing if an earlier strategy has requested a redirect, with the possibility to cancel it. I can see a few use cases for this (`ReleaseModeOnly`, `ThrowIfLocal`, etc).

I am currently leaning towards #3, even though it means changing all existing strategies slightly. While it seems wrong to make such breaking change just after releasing v1.0, i don't think it will harm a lot of people with < 30 downloads in total. I would love to hear your thoughts. Do you have any other ideas on how to solve the issue?

**Comment by chripede** [comment]
My quick fix would have been an `bool ignorePort` parameter, but I like suggestion #3.

I'll be happy to help test v2.0 :)

**Comment by schourode** [comment]
Whoops, sorry for disappearing on you here – I have been extremely busy for the past weeks, but I am back now.

After doing some [experiments with HTTP headers on AppHarbor](http://appharbor-http-test.apphb.com) and giving this some more thought, I have decided on a way to solve this issue without changing the API in any way. Basically, rather than hoping for `HttpRequest.Url` to contain the true input URL, the upcoming version of Canonicalize will manually process a few HTTP headers to get the correct starting point:
- Host
- X-Forwarded-Host
- X-Forwarded-Proto

I will let you know as soon as the patch is ready, and would love for you to try it out in a real-life setup before I push a new version to NuGet. Stay tuned!

**Comment by schourode** [comment]
Go ahead and do a fresh build from the source in this repository now, and I believe the issue should be fixed. Let me know if it really works with your AppHarbor setup – I will stand by for a fresh NuGet release :)
