### ISSUE TITLE
MVC 4.0 and Route Registration

### ISSUE THREAD

**Issue by jednano** [schourode/canonicalize#2]
Perhaps I'm doing it wrong, but have you gotten this to work with MVC 4.0? I have the following in my route registration, as the documentation says, before any existing registrations; yet, it doesn't appear to be working (i.e. my URLs are still camel case and such). I'm just using the default registrations in a fresh MVC 4.0 install, like so...

```
public static void RegisterRoutes(RouteCollection routes)
{
    routes.Canonicalize().NoWww().Pattern("([a-z0-9])([A-Z])", "$1-$2").Lowercase().NoTrailingSlash();

    routes.IgnoreRoute("{resource}.axd/{*pathInfo}");

    routes.MapRoute(
        "Default", // Route name
        "{controller}/{action}/{id}", // URL with parameters
        new { controller = "Home", action = "Index", id = UrlParameter.Optional } // Parameter defaults
    );
}
```

Should I not be using the MapRoute method like that?

Notice, I've added a pattern in the hopes that I can replace camel case urls with hyphens instead; though, I'm looking for a better solution, as I know this wouldn't work anyway. I'm just looking for a way to enforce hypens w/o changing the names of the ActionResults.

**Comment by schourode** [comment]
Sorry about the delay in answering - the notification mail went below the radar, and I only discovered the issue report today.

I have not had a chance to try out ASP.NET MVC 4 myself, so I cannot say for sure if Canonicalize works with the new framework. However, I would expect it to work just fine, since Canonicalize does not do anything "exotic".

In your application, what would you expect should happen if a request is made to the path `/fooBar`? Canonicalize is supposed to handle the request by returning status code `301 Moved permanently` pointing to the new path `/foo-bar`. The browser will then make a request to this new URL, and now it is up to your URL mappings to forward the request to the relevant controller.

Is this not what you see happening? I have a feeling you might be expecting Canonicalize to do something more, rewriting the URL in the opposite direction (`/foo-bar` to `/fooBar`) before it is passed on to your routes. That it will not do.

Does this answer your question, or am I missing your point entirely?

**Comment by jednano** [comment]
Actually, I don't know why it wasn't working at first, but somehow it started working. Could have been a caching issue. Anyway, I ended up removing the .Pattern() because I needed the hover URLs to also be hyphenated, instead of just the routes. If it changes at the point of the routes then it's already too late. That is, the user could right-click on a link and copy it and it would still be fooBar, instead of foo-bar. This is bad, because search engines and such will see 2 completely different links that point to the same content.

I'm still using Canonicalize for the .NoWww().Lowercase().NoTrailingSlash() though. Great tool!
